### ISSUE TITLE
There was error when connecting websocket

### ISSUE THREAD

**Issue by mhwahyudi** [tiredofit/docker-baserow#10]
Hi Folks,

I Just installed the baserow image https://hub.docker.com/r/tiredofit/baserow in my kubernetes cluster (V1.21.4), The installation was successfully but when I create account and login into dashboard I got error show on dev tools chrome console. The was error access from websocket like below.

```
WebSocket connection to 'wss://api-baserow.xxx.com/ws/core/?jwt_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.c2VyX2lkIjoxLCJ1c2VybmFtZSI6Imp2c3NpcGF5dW5nQHdhcmVzaXguY29tIiwiZXhwIjoxNjQxMzc1NTcyLCJlbWFpbCI6Imp2c3NpcGF5dW5nQHdhcmVzaXguY29tIiwib3JpZ19pYXQiOjE2NDEzNjk1ODR9.csiotNq81knXQXRdXX7nba6G5HQdExIvC_mLaEijytQ' failed: 
WebSocket connection to 'wss://api-baserow.xxx.com/ws/core/?jwt_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.c2VyX2lkIjoxLCJ1c2VybmFtZSI6Imp2c3NpcGF5dW5nQHdhcmVzaXguY29tIiwiZXhwIjoxNjQxMzc1NTcyLCJlbWFpbCI6Imp2c3NpcGF5dW5nQHdhcmVzaXguY29tIiwib3JpZ19pYXQiOjE2NDEzNjk1ODR9.csiotNq81knXQXRdXX7nba6G5HQdExIvC_mLaEijytQ' failed: 
WebSocket connection to 'wss://api-baserow.xxx.com/ws/core/?jwt_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.c2VyX2lkIjoxLCJ1c2VybmFtZSI6Imp2c3NpcGF5dW5nQHdhcmVzaXguY29tIiwiZXhwIjoxNjQxMzc1NTcyLCJlbWFpbCI6Imp2c3NpcGF5dW5nQHdhcmVzaXguY29tIiwib3JpZ19pYXQiOjE2NDEzNjk1ODR9.csiotNq81knXQXRdXX7nba6G5HQdExIvC_mLaEijytQ' failed: 
WebSocket connection to 'wss://api-baserow.xxx.com/ws/core/?jwt_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.c2VyX2lkIjoxLCJ1c2VybmFtZSI6Imp2c3NpcGF5dW5nQHdhcmVzaXguY29tIiwiZXhwIjoxNjQxMzc1NTcyLCJlbWFpbCI6Imp2c3NpcGF5dW5nQHdhcmVzaXguY29tIiwib3JpZ19pYXQiOjE2NDEzNjk1ODR9.csiotNq81knXQXRdXX7nba6G5HQdExIvC_mLaEijytQ' failed: 
```
Here is error from pod
```
[2022-01-05 08:01:25 +0000] [1109] [DEBUG] GET /ws/core/
Not Found: /ws/core/
[2022-01-05 08:01:32 +0000] [1106] [DEBUG] POST /api/groups/
Internal Server Error: /api/groups/
Traceback (most recent call last):
  File "/app/backend/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "trashed" violates not-null constraint
DETAIL:  Failing row contains (32, Test group, 2022-01-05 08:01:32.699809+00, 2022-01-05 08:01:32.699846+00, null).


The above exception was the direct cause of the following exception:
```
Here my deployment.yml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baserow-app
  namespace: data-tools
  labels:
    app: baserow-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baserow-app
  template:
    metadata:
      labels:
        app: baserow-app
    spec:
      containers:
      - name: baserow-app
        image: tiredofit/baserow
        ports:
        - containerPort: 80
        env:
        - name: API_HOSTNAME
          value: "api-baserow.xxx.com"
        - name: API_PROTOCOL
          value: "https"
        - name: APPLICATION_HOSTNAME
          value: "baserow.xxx.com"
        - name: APPLICATION_PROTOCOL
          value: "https"
        - name: APP_DEBUG
          value: "True"
        - name: BACKEND_WORKERS
          value: "5"
        - name: DB_HOST
          value: "host-db"
        - name: DB_NAME
          value: "db-name"
        - name: DB_PASS
          value: "pass-db"
        - name: DB_PORT
          value: "5432"
        - name: DB_TYPE
          value: "postgresql"
        - name: DB_USER 
          value: "user-db"
        - name: INTERNAL_API_HOST
          value: "0.0.0.0"
        - name: INTERNAL_API_LISTEN_PORT
          value: "8000"
        - name: INTERNAL_API_PROTOCOL
          value: "http"
        - name: LANGUAGE
          value: "en-us"
        - name: LOG_LEVEL
          value: "debug"
        - name: MODE
          value: "AIO"
        - name: PASSWORD_RESET_MAX_AGE
          value: "1"
        - name: MEDIA_HOSTNAME
          value: "media-baserow.xxx.com"
        volumeMounts:
        - name: nginx-logs
          mountPath: /www/logs
      volumes:
      - name: nginx-logs
        emptyDir: {}
```
and here is my service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: baserow-service 
  namespace: data-tools
spec:
  selector:
    app: baserow-app 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
```
Is there anybody that got error like me, need  an advice.
